Repository aurelia/aurelia, pull requests merged in 2018-12, with the labels that each got.

#333 refactor(kernel): strictNullChecks fixes
  packages/kernel/src/di.ts
Labels: scope: chore, status: ready

#334 refactor(plugin-requirejs): strictNullChecks fixes
  packages/plugin-requirejs/src/processing.ts
Labels: scope: chore, status: ready

#335 refactor(plugin-svg): strictNullChecks fixes
  packages/plugin-svg/src/svg-analyzer.ts
Labels: scope: chore, status: ready

#336 refactor(runtime): strictNullChecks fixes
  packages/runtime/src/binding/ast.ts
  packages/runtime/src/binding/binding-context.ts
  packages/runtime/src/definitions.ts
  packages/runtime/src/dom.ts
  packages/runtime/src/lifecycle.ts
  packages/runtime/src/resource.ts
  packages/runtime/src/templating/custom-attribute.ts
  packages/runtime/src/templating/custom-element.ts
  packages/runtime/src/templating/lifecycle-render.ts
  packages/runtime/src/templating/resources/compose.ts
  packages/runtime/src/templating/resources/if.ts
  packages/runtime/src/templating/resources/repeat.ts
  packages/runtime/src/templating/resources/with.ts
  packages/runtime/src/templating/view.ts
Labels: scope: chore, status: ready

#337 Linting fixes
  packages/debug/src/binding/unparser.ts
  packages/jit/src/attribute-parser.ts
  packages/jit/src/attribute-pattern.ts
  packages/jit/src/common.ts
  packages/jit/src/element-parser.ts
  packages/jit/src/expression-parser.ts
  packages/kernel/src/di.ts
  packages/plugin-requirejs/src/processing.ts
  packages/plugin-requirejs/src/types.ts
  packages/plugin-requirejs/src/view.ts
  packages/runtime/src/binding/ast.ts
  packages/runtime/src/binding/binding-context.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/connectable.ts
  packages/runtime/src/binding/dirty-checker.ts
  packages/runtime/src/binding/event-manager.ts
  packages/runtime/src/binding/expression-parser.ts
  packages/runtime/src/binding/observer-locator.ts
  packages/runtime/src/binding/resources/debounce-binding-behavior.ts
  packages/runtime/src/binding/resources/self-binding-behavior.ts
  packages/runtime/src/binding/resources/throttle-binding-behavior.ts
  packages/runtime/src/binding/signaler.ts
  packages/runtime/src/definitions.ts
  packages/runtime/src/dom.ts
  packages/runtime/src/html-renderer.ts
  packages/runtime/src/lifecycle.ts
  packages/runtime/src/observation.ts
  packages/runtime/src/templating/create-element.ts
  packages/runtime/src/templating/custom-attribute.ts
  packages/runtime/src/templating/custom-element.ts
  packages/runtime/src/templating/lifecycle-attach.ts
  packages/runtime/src/templating/lifecycle-bind.ts
  packages/runtime/src/templating/lifecycle-render.ts
  packages/runtime/src/templating/resources/if.ts
  packages/runtime/src/templating/view.ts
Labels: scope: chore, status: ready

#339 chore(examples): update gulp semver range to reflect 4.0.0 release
  examples/jit-aurelia-cli-ts/package.json
  examples/jit-browserify-ts/package.json
  test/wdio/cases/dev/jit-aurelia-cli-ts/package.json
  test/wdio/cases/dev/jit-browserify-ts/package.json
  test/wdio/cases/latest/jit-aurelia-cli-ts/package.json
  test/wdio/cases/latest/jit-browserify-ts/package.json
  test/wdio/cases/local/jit-aurelia-cli-ts/package.json
  test/wdio/cases/local/jit-browserify-ts/package.json
Labels: scope: chore, status: ready

#315 [WIP] Router
  packages/router/.vscode/settings.json
  packages/router/src/history-browser.ts
  packages/router/src/index.ts
  packages/router/src/link-handler.ts
  packages/router/src/resources/viewport.ts
  packages/router/src/router.ts
  packages/router/src/scope.ts
  packages/router/src/viewport.ts
  packages/router/test/e2e/modules/.npmrc
  packages/router/test/e2e/modules/README.md
  packages/router/test/e2e/modules/gulpfile.js
  packages/router/test/e2e/modules/index.html
  packages/router/test/e2e/modules/package.json
  packages/router/test/e2e/modules/src/app-state.ts
  packages/router/test/e2e/modules/src/app.html
  packages/router/test/e2e/modules/src/app.ts
  packages/router/test/e2e/modules/src/components/abc-component.html
  packages/router/test/e2e/modules/src/components/abc-component.ts
  packages/router/test/e2e/modules/src/components/about.ts
  packages/router/test/e2e/modules/src/components/alpha.ts
  packages/router/test/e2e/modules/src/components/beta.ts
  packages/router/test/e2e/modules/src/components/calendar.html
  packages/router/test/e2e/modules/src/components/calendar.ts
  packages/router/test/e2e/modules/src/components/contacts.ts
  packages/router/test/e2e/modules/src/components/dates.ts
  packages/router/test/e2e/modules/src/components/def-component.html
  packages/router/test/e2e/modules/src/components/def-component.ts
  packages/router/test/e2e/modules/src/components/email.html
  packages/router/test/e2e/modules/src/components/email.ts
  packages/router/test/e2e/modules/src/components/goto.html
  packages/router/test/e2e/modules/src/components/goto.ts
  packages/router/test/e2e/modules/src/components/header.ts
  packages/router/test/e2e/modules/src/components/inbox.ts
  packages/router/test/e2e/modules/src/components/one.html
  packages/router/test/e2e/modules/src/components/one.ts
  packages/router/test/e2e/modules/src/components/recursive.html
  packages/router/test/e2e/modules/src/components/recursive.ts
  packages/router/test/e2e/modules/src/components/schedule.ts
  packages/router/test/e2e/modules/src/components/sub.ts
  packages/router/test/e2e/modules/src/components/three.html
  packages/router/test/e2e/modules/src/components/three.ts
  packages/router/test/e2e/modules/src/components/two.html
  packages/router/test/e2e/modules/src/components/two.ts
  packages/router/test/e2e/modules/src/html.d.ts
  packages/router/test/e2e/modules/src/startup.ts
  packages/router/test/e2e/modules/tsconfig.json
  packages/router/test/mock/browser-history-location.mock.ts
  packages/router/test/unit/README.md
  packages/router/test/unit/history-browser.spec.ts
  packages/router/test/unit/index.spec.ts
  packages/router/test/unit/link-handler.spec.ts
  packages/router/test/unit/router.spec.ts
  packages/router/test/unit/viewport.spec.ts
  packages/router/tsconfig.json
Labels: status: WIP

#342 chore(all): add script to bundle only a single package
  packages/aot/package.json
  packages/debug/package.json
  packages/jit/package.json
  packages/kernel/package.json
  packages/plugin-parcel/package.json
  packages/plugin-requirejs/package.json
  packages/plugin-svg/package.json
  packages/plugin-webpack/package.json
  packages/router/package.json
  packages/runtime/package.json
  packages/testing/package.json
  packages/validation/package.json
  scripts/bundle.ts
Labels: scope: chore, status: ready

#343 fix(template-binder): correctly traverse not-compilable node types
  packages/jit/src/template-binder.ts
  packages/jit/test/integration/template-compiler.kitchen-sink.spec.ts
Labels: scope: minor changes, status: ready

#351 test(browserstack): switch to webpack to fix the e2e job
  test/browserstack/package-lock.json
  test/browserstack/package.json
  test/browserstack/tsconfig.json
  test/browserstack/webpack.config.js
Labels: status: ready

#355 Fix local deps
  .vscode/launch.json
  packages/jit-html/test/integration/template-compiler.compose.spec.ts
  packages/jit-html/test/integration/template-compiler.kitchen-sink.spec.ts
  packages/kernel/src/di.ts
  packages/kernel/src/resource.ts
  packages/kernel/test/di.spec.ts
  packages/router/src/viewport.ts
  packages/runtime-html/src/create-element.ts
  packages/runtime/src/aurelia.ts
  packages/runtime/src/renderer.ts
  packages/runtime/src/rendering-engine.ts
  packages/runtime/src/resources/custom-element.ts
  packages/runtime/src/templating/lifecycle-render.ts
  packages/runtime/test/au-dom.ts
  packages/runtime/test/resources/custom-element.dependencies.spec.ts
  packages/runtime/test/template.spec.ts
  packages/runtime/test/templating/custom-element.$hydrate.spec.ts
Labels: scope: minor changes, status: ready
