Repository aurelia/aurelia, pull requests merged in 2018-11, with the labels that each got.

#283 refactor: changes to AST to help enable strictPropertyInitialization
  packages/runtime/src/aurelia.ts
  packages/runtime/src/binding/ast.ts
Labels: scope: chore, scope: minor changes, status: ready

#286 refactor: add typeguards to decorators and rename Source to Definition
  packages/jit/src/binding-command.ts
  packages/jit/src/template-compiler.ts
  packages/jit/test/integration/prepare.ts
  packages/runtime/src/aurelia.ts
  packages/runtime/src/binding/binding-behavior.ts
  packages/runtime/src/binding/value-converter.ts
  packages/runtime/src/definitions.ts
  packages/runtime/src/html-renderer.ts
  packages/runtime/src/resource.ts
  packages/runtime/src/templating/create-element.ts
  packages/runtime/src/templating/custom-attribute.ts
  packages/runtime/src/templating/custom-element.ts
  packages/runtime/src/templating/lifecycle-attach.ts
  packages/runtime/src/templating/lifecycle-bind.ts
  packages/runtime/src/templating/lifecycle-render.ts
  packages/runtime/src/templating/resources/compose.ts
  packages/runtime/src/templating/resources/if.ts
  packages/runtime/src/templating/resources/repeat.ts
  packages/runtime/src/templating/resources/replaceable.ts
  packages/runtime/src/templating/resources/with.ts
Labels: scope: chore, scope: minor changes, status: ready

#287 refactor: fix errors and warnings reported by "lgtm"
  examples/jit-browserify-ts/gulpfile.js
  packages/debug/src/binding/unparser.ts
  packages/examples/dbmonster-a/lib/ENV.js
  packages/examples/dbmonster-a/lib/memory-stats.js
  packages/examples/dbmonster-a/lib/monitor.js
  packages/examples/dbmonster-b/lib/ENV.js
  packages/examples/dbmonster-b/lib/memory-stats.js
  packages/examples/dbmonster-b/lib/monitor.js
  packages/examples/e2e-benchmark/e2e/page-objects/app.page.ts
  packages/examples/fractals/src/pythagoras.ts
  packages/examples/fractals/src/startup.ts
  packages/kernel/src/di.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/target-accessors.ts
  scripts/post-allure.ts
Labels: scope: chore, status: ready

#292 ci: move the nightly build 5 hours back
  .circleci/config.yml
Labels: scope: chore, status: ready

#291 feat(aurelia): add startup api shorthand
  packages/jit/test/integration/template-compiler.kitchen-sink.spec.ts
  packages/runtime/src/aurelia.ts
Labels: scope: minor changes, status: feedback requested, status: ready

#289 refactor(runtime): changes to Binding for strictPropertyInitialization
  packages/runtime/src/binding/binding-context.ts
  packages/runtime/src/binding/binding.ts
  packages/runtime/src/binding/call.ts
  packages/runtime/src/binding/collection-observer.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/dirty-checker.ts
  packages/runtime/src/binding/element-observation.ts
  packages/runtime/src/binding/event-manager.ts
  packages/runtime/src/binding/expression-parser.ts
  packages/runtime/src/binding/interpolation-binding.ts
  packages/runtime/src/binding/let-binding.ts
  packages/runtime/src/binding/listener.ts
  packages/runtime/src/binding/observer-locator.ts
  packages/runtime/src/binding/ref.ts
  packages/runtime/src/binding/resources/binding-mode-behaviors.ts
  packages/runtime/src/binding/resources/sanitize.ts
  packages/runtime/src/binding/resources/signals.ts
  packages/runtime/src/binding/resources/update-trigger-binding-behavior.ts
  packages/runtime/src/binding/target-accessors.ts
Labels: scope: chore, scope: minor changes, status: ready

#294 refactor(runtime): remove StrictAny in favor of unknown
  packages/kernel/src/platform.ts
  packages/kernel/src/reporter.ts
  packages/runtime/src/binding/ast.ts
  packages/runtime/src/binding/binding-context.ts
  packages/runtime/src/binding/binding.ts
  packages/runtime/src/binding/call.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/connectable.ts
  packages/runtime/src/binding/interpolation-binding.ts
  packages/runtime/src/binding/let-binding.ts
  packages/runtime/src/binding/listener.ts
  packages/runtime/src/binding/ref.ts
  packages/runtime/src/binding/set-observer.ts
  packages/runtime/src/dom.ts
  packages/runtime/src/lifecycle.ts
  packages/runtime/src/observation.ts
  packages/runtime/src/templating/resources/repeat.ts
Labels: scope: chore, scope: minor changes, status: ready

#296 view compiler extension point (part 1/2)
  packages/jit/src/ast.ts
  packages/jit/src/attribute-parser.ts
  packages/jit/src/attribute-pattern.ts
  packages/jit/src/configuration.ts
  packages/jit/src/element-parser.ts
  packages/jit/src/index.ts
  packages/jit/src/semantic-model.ts
  packages/jit/test/unit/attribute-pattern.spec.ts
  packages/jit/test/unit/template-compiler.spec.ts
  packages/kernel/src/di.ts
Labels: scope: medium changes, status: ready

#297 refactor: more any to strict typing conversions
  packages/jit/src/binding-command.ts
  packages/jit/src/semantic-model.ts
  packages/kernel/src/di.ts
  packages/plugin-requirejs/src/processing.ts
  packages/runtime/src/binding/binding-context.ts
  packages/runtime/src/binding/binding.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/let-binding.ts
  packages/runtime/src/binding/observer-locator.ts
  packages/runtime/src/binding/resources/attr-binding-behavior.ts
  packages/runtime/src/binding/resources/debounce-binding-behavior.ts
  packages/runtime/src/definitions.ts
  packages/runtime/src/dom.ts
  packages/runtime/src/html-renderer.ts
  packages/runtime/src/instructions.ts
  packages/runtime/src/observation.ts
  packages/runtime/src/templating/create-element.ts
  packages/runtime/src/templating/resources/compose.ts
  packages/runtime/src/templating/resources/repeat.ts
  packages/runtime/src/templating/resources/with.ts
  packages/runtime/src/templating/view.ts
  tslint.json
Labels: scope: chore, status: ready

#301 refactor: partially revert renames due to no-reserved-keywords
  packages/debug/src/reporter.ts
  packages/runtime/src/binding/array-observer.ts
  packages/runtime/src/definitions.ts
Labels: scope: chore, status: ready

#304 refactor: fix no-floating-promises linting warnings
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/subscriber-collection.ts
  packages/runtime/src/binding/target-observer.ts
  packages/runtime/src/lifecycle.ts
  packages/runtime/src/templating/lifecycle-render.ts
  packages/runtime/src/templating/resources/if.ts
Labels: scope: chore, status: ready

#305 perf(all): shorten au-marker to au-m
  packages/examples/dbmonster-a/app-config.ts
  packages/examples/test-aot/app-config.ts
  packages/jit/src/ast.ts
  packages/jit/src/semantic-model.ts
  packages/jit/test/unit/template-compiler.spec.ts
  packages/runtime/src/dom.ts
  packages/runtime/test/unit/mock.ts
  packages/runtime/test/unit/util.ts
Labels: scope: chore, status: ready

#308 refactor(kernel): linting fixes for di
  packages/kernel/src/di.ts
  packages/runtime/src/binding/target-accessors.ts
  tslint.json
Labels: scope: chore, status: ready

#309 refactor: linting fixes for IIndexable
  packages/jit/src/binding-command.ts
  packages/kernel/src/interfaces.ts
  packages/runtime/src/binding/array-observer.ts
  packages/runtime/src/binding/call.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/dirty-checker.ts
  packages/runtime/src/binding/element-observation.ts
  packages/runtime/src/binding/map-observer.ts
  packages/runtime/src/binding/observer-locator.ts
  packages/runtime/src/binding/property-observation.ts
  packages/runtime/src/binding/set-observer.ts
  packages/runtime/src/binding/subscriber-collection.ts
  packages/runtime/src/binding/target-accessors.ts
  packages/runtime/src/binding/target-observer.ts
  packages/runtime/src/observation.ts
  packages/runtime/src/templating/create-element.ts
Labels: scope: chore, status: ready

#313 refactor(runtime): changes to Templating for strictPropertyInitialization
  packages/runtime/src/dom.ts
  packages/runtime/src/instructions.ts
  packages/runtime/src/lifecycle.ts
  packages/runtime/src/resource.ts
  packages/runtime/src/templating/create-element.ts
  packages/runtime/src/templating/lifecycle-render.ts
  packages/runtime/src/templating/resources/compose.ts
  packages/runtime/src/templating/resources/if.ts
  packages/runtime/src/templating/resources/repeat.ts
  packages/runtime/src/templating/resources/replaceable.ts
  packages/runtime/src/templating/resources/with.ts
  packages/runtime/src/templating/view.ts
Labels: scope: chore, status: ready

#310 refactor: add Sonarts linting rules
  package-lock.json
  package.json
  packages/aot/package.json
  packages/debug/package.json
  packages/jit/package.json
  packages/jit/src/expression-parser.ts
  packages/jit/src/semantic-model.ts
  packages/jit/src/template-compiler.ts
  packages/kernel/package.json
  packages/kernel/src/interfaces.ts
  packages/plugin-parcel/package.json
  packages/plugin-requirejs/package.json
  packages/plugin-requirejs/src/component.ts
  packages/plugin-requirejs/src/processing.ts
  packages/plugin-requirejs/src/view.ts
  packages/plugin-svg/package.json
  packages/plugin-webpack/package.json
  packages/router/package.json
  packages/runtime/package.json
  packages/runtime/src/binding/array-observer.ts
  packages/runtime/src/binding/binding-context.ts
  packages/runtime/src/binding/binding.ts
  packages/runtime/src/binding/computed-observer.ts
  packages/runtime/src/binding/element-observation.ts
  packages/runtime/src/binding/event-manager.ts
  packages/runtime/src/binding/expression-parser.ts
  packages/runtime/src/binding/interpolation-binding.ts
  packages/runtime/src/binding/let-binding.ts
  packages/runtime/src/binding/observer-locator.ts
  packages/runtime/src/binding/target-observer.ts
  packages/runtime/src/definitions.ts
  packages/runtime/src/lifecycle.ts
  packages/runtime/src/observation.ts
  packages/runtime/src/templating/lifecycle-attach.ts
  packages/runtime/src/templating/resources/repeat.ts
  packages/testing/package.json
  packages/validation/package.json
  tslint.json
Labels: scope: chore, scope: minor changes, status: ready
