Repository aurelia/aurelia, pull requests merged in 2019-10, with the labels that each got.

#689 chore: disable codeclimate Mainenance Checks
  .codeclimate.yml
Labels: Topic: Code quality

#690 refactor: drop unused imports
  packages/__tests__/jit-html/blur.integration.spec.ts
  packages/__tests__/jit-html/repeat.integration.spec.ts
  packages/__tests__/jit-html/template-compiler.primary-bindable.spec.ts
  packages/__tests__/router/configuration.spec.ts
  packages/__tests__/router/e2e/doc-example/app/src/app.ts
  packages/__tests__/router/instruction-resolver.spec.ts
  packages/i18n/src/t/translation-binding.ts
  packages/jit/src/attribute-pattern.ts
  packages/kernel/src/di.ts
  packages/router/src/configuration.ts
  packages/runtime-html/src/binding/attribute.ts
  packages/runtime-html/src/binding/listener.ts
  packages/runtime-html/src/create-element.ts
  packages/runtime-html/src/html-renderer.ts
  packages/runtime-html/src/observation/select-value-observer.ts
  packages/runtime-html/src/projectors.ts
  packages/runtime/src/aurelia.ts
  packages/runtime/src/binding/call-binding.ts
  packages/runtime/src/binding/connectable.ts
  packages/runtime/src/binding/let-binding.ts
  packages/runtime/src/binding/property-binding.ts
  packages/runtime/src/binding/ref-binding.ts
  packages/runtime/src/observation/array-observer.ts
  packages/runtime/src/observation/binding-context.ts
  packages/runtime/src/observation/computed-observer.ts
  packages/runtime/src/observation/dirty-checker.ts
  packages/runtime/src/observation/map-observer.ts
  packages/runtime/src/observation/primitive-observer.ts
  packages/runtime/src/observation/property-accessor.ts
  packages/runtime/src/observation/proxy-observer.ts
  packages/runtime/src/observation/set-observer.ts
  packages/runtime/src/observation/setter-observer.ts
  packages/runtime/src/rendering-engine.ts
  packages/runtime/src/templating/view.ts
  packages/testing/src/au-dom.ts
  test/js-framework-benchmark/results-ui/src/ui.js
  test/js-framework-benchmark/webdriver-ts/src/benchmarkRunner.ts
  test/js-framework-benchmark/webdriver-ts/src/benchmarks.ts
  test/js-framework-benchmark/webdriver-ts/src/buildDockerFrameworks.ts
  test/js-framework-benchmark/webdriver-ts/src/createIndex.ts
  test/js-framework-benchmark/webdriver-ts/src/createResultJS.ts
  test/js-framework-benchmark/webdriver-ts/src/forkedBenchmarkRunner.ts
  test/js-framework-benchmark/webdriver-ts/src/isKeyed.ts
  test/js-framework-benchmark/webdriver-ts/src/rebuild.ts
  test/js-framework-benchmark/webdriver-ts/src/updateFrameworks.ts
  test/js-framework-benchmark/webdriver-ts/src/webdriverAccess.ts
  test/realworld/src/main.ts
Labels: Topic: Code quality

#702 test: fix browserstack error
  scripts/logger.ts
Labels: Topic: Testing

#704 chore: switch to no-hooks
  packages/__tests__/.eslintrc.js
  packages/__tests__/i18n/t/translation-integration.spec.ts
  packages/__tests__/i18n/t/translation-render.spec.ts
  packages/__tests__/jit-html/blur.integration.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.double.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.double.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.spec.ts
  packages/__tests__/jit-html/template-compiler.harmony.spec.ts
  packages/__tests__/jit-html/template-compiler.ref.spec.ts
  packages/__tests__/jit-html/template-compiler.spec.ts
  packages/__tests__/jit-html/template-element-factory.spec.ts
  packages/__tests__/kernel/di.integration.spec.ts
  packages/__tests__/kernel/di.spec.ts
  packages/__tests__/runtime-html/attr-binding-behavior.spec.ts
  packages/__tests__/runtime-html/checked-observer.spec.ts
  packages/__tests__/runtime-html/dom.spec.ts
  packages/__tests__/runtime-html/self-binding-behavior.spec.ts
  packages/__tests__/runtime/array-observer.spec.ts
  packages/__tests__/runtime/ast.spec.ts
  packages/__tests__/runtime/binding-behavior.spec.ts
  packages/__tests__/runtime/binding-mode-behaviors.spec.ts
  packages/__tests__/runtime/binding.spec.ts
  packages/__tests__/runtime/debounce-binding-behavior.spec.ts
  packages/__tests__/runtime/dirty-checker.spec.ts
  packages/__tests__/runtime/throttle-binding-behavior.spec.ts
  packages/__tests__/runtime/value-converter.spec.ts
  scripts/generate-tests/template-compiler.static.ts
  scripts/generate-tests/util.ts
Labels: Topic: Code quality

#703 chore: move inline eslint disables to .eslintrc.js for generated tests
  packages/__tests__/.eslintrc.js
  packages/__tests__/jit-html/generated/template-compiler.mutations.basic.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.double.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.double.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.repeat.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.if-else.spec.ts
  packages/__tests__/jit-html/generated/template-compiler.static.spec.ts
  scripts/generate-tests/util.ts
Labels: Topic: Code quality

#705 chore: lint prefer-const
  .eslintrc.js
  examples/jit-fuse-box-ts/fuse.js
  packages/__tests__/i18n/t/translation-integration.spec.ts
  packages/__tests__/jit-html/blur.unit.spec.ts
  packages/__tests__/router/instruction-resolver.spec.ts
  packages/__tests__/runtime/if.integration.spec.ts
  packages/jit-html/src/template-compiler.ts
  packages/kernel/src/platform.ts
  packages/runtime-html/src/resources/custom-attributes/blur.ts
  packages/runtime/src/binding/ast.ts
  packages/runtime/src/observation/observer-locator.ts
  test/fractals-tree/state.js
  test/js-framework-benchmark/build.js
  test/js-framework-benchmark/cleanup.js
  test/js-framework-benchmark/configureStyles.js
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/attribute.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/binding-behavior.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/component.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/element.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/generator.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/task.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/value-converter.ts
  test/js-framework-benchmark/frameworks/keyed/vanillajs/src/Main.js
  test/js-framework-benchmark/results-ui/src/build.js
  test/js-framework-benchmark/webdriver-ts/src/benchmarkRunner.ts
  test/js-framework-benchmark/webdriver-ts/src/benchmarks.ts
  test/js-framework-benchmark/webdriver-ts/src/buildDockerFrameworks.ts
  test/js-framework-benchmark/webdriver-ts/src/common.ts
  test/js-framework-benchmark/webdriver-ts/src/createIndex.ts
  test/js-framework-benchmark/webdriver-ts/src/createResultJS.ts
  test/js-framework-benchmark/webdriver-ts/src/forkedBenchmarkRunner.ts
  test/js-framework-benchmark/webdriver-ts/src/isKeyed.ts
  test/js-framework-benchmark/webdriver-ts/src/rebuild.ts
  test/js-framework-benchmark/webdriver-ts/src/updateFrameworks.ts
  test/js-framework-benchmark/webdriver-ts/src/webdriverAccess.ts
  test/rainbow-spiral/app.js
  test/rainbow-spiral/state.js
  test/sierpinski-triangle/app.js
Labels: Topic: Code quality

#701 test: require node >= 12.0.0
  packages/__tests__/package.json
Labels: Topic: Testing

#712 chore: lint no-var
  .eslintrc.js
  test/browserstack/browserstack.conf.ts
  test/js-framework-benchmark/build.js
  test/js-framework-benchmark/cleanup.js
  test/js-framework-benchmark/configureStyles.js
  test/js-framework-benchmark/copy.js
  test/js-framework-benchmark/frameworks/keyed/aurelia/aurelia_project/generators/component.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/src/app.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/src/aurelia-polyfills.js
  test/js-framework-benchmark/frameworks/keyed/aurelia/src/store.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia/types/system.d.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia2-local/src/app.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia2-local/src/source.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia2-npm/src/app.ts
  test/js-framework-benchmark/frameworks/keyed/aurelia2-npm/src/source.ts
  test/js-framework-benchmark/frameworks/keyed/vanillajs/src/Main.js
  test/js-framework-benchmark/frameworks/keyed/vanillajs/webpack.config.js
  test/js-framework-benchmark/results-ui/src/build.js
  test/js-framework-benchmark/results-ui/src/ui.js
  test/js-framework-benchmark/webdriver-ts-results/webpack.config.js
  test/js-framework-benchmark/webdriver-ts/src/buildDockerFrameworks.ts
  test/js-framework-benchmark/webdriver-ts/src/forkedBenchmarkRunner.ts
  test/js-framework-benchmark/webdriver-ts/src/isKeyed.ts
  test/js-framework-benchmark/webdriver-ts/src/rebuild.ts
  test/js-framework-benchmark/webdriver-ts/src/updateFrameworks.ts
  test/js-framework-benchmark/webdriver-ts/src/webdriverAccess.ts
Labels: Topic: Code quality

#713 chore: fix Deepscan issues
  examples/jit-pixi-webpack-ts/webpack.config.js
  packages/__tests__/jit-html/focus.spec.ts
  packages/__tests__/karma.conf.js
  packages/__tests__/router/e2e/layouts/gulpfile.js
  packages/__tests__/router/e2e/modules/gulpfile.js
  packages/examples/dbmonster-b/lib/memory-stats.js
  packages/examples/requirejs/view.js
  packages/jit/src/expression-parser.ts
  packages/testing/src/h.ts
  packages/testing/src/specialized-assertions.ts
  test/1kcomponents/app-double.js
  test/1kcomponents/app.js
  test/js-framework-benchmark/webdriver-ts-results/webpack.config.js
  test/js-framework-benchmark/webdriver-ts/src/common.ts
Labels: Topic: Code quality

#717 Fix multi binding compilation
  packages/__tests__/jit-html/portal.spec.tsx
  packages/__tests__/jit-html/template-compiler.primary-bindable.spec.ts
  packages/jit-html/src/template-binder.ts
Labels: Bug
